# Generated by Django 5.1.6 on 2025-03-14 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, default='product.png', null=True, upload_to='Training_Image')),
                ('video', models.FileField(upload_to='videos/')),
                ('duration', models.PositiveIntegerField()),
                ('document', models.FileField(blank=True, null=True, upload_to='lessons/')),
                ('status', models.CharField(choices=[('Debutant', 'Debutant'), ('Intermediare', 'Intermediare'), ('Avancee', 'Avancee')], default='Debutant', max_length=25)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('students', models.ManyToManyField(blank=True, related_name='courses_followed', to=settings.AUTH_USER_MODEL)),
                ('trainer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_taught', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('video', models.FileField(upload_to='videos/')),
                ('duration', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('Premium', 'Premium'), ('Gratuit', 'Gratuit')], default='Gratuit', max_length=25)),
                ('order', models.PositiveIntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='TrainingCourses.course')),
            ],
        ),
        migrations.CreateModel(
            name='SkillsLearn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='TrainingCourses.course')),
            ],
        ),
    ]
