# Generated by Django 5.1.6 on 2025-03-17 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrainingCourses', '0002_alter_modules_options_alter_skillslearn_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='document',
        ),
        migrations.AddField(
            model_name='modules',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='lessons/'),
        ),
    ]
