# Generated by Django 5.1.6 on 2025-03-17 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TrainingCourses', '0003_remove_course_document_modules_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='video',
        ),
    ]
