# Generated by Django 5.1.6 on 2025-03-18 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrainingCourses', '0006_alter_course_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='boosted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
