# Generated by Django 5.1.6 on 2025-03-20 18:46

import django.db.models.deletion
import shortuuid.django_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductListings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.CharField(max_length=255)),
                ('Description', models.TextField()),
                ('Published_Date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, default='product.png', null=True, upload_to='Computer_image')),
                ('is_sponsored', models.BooleanField(blank=True, default=False, null=True)),
                ('status', models.CharField(choices=[('Published', 'Published'), ('Disabled', 'Disabled'), ('isSponsored', 'isSponsored')], default='Published', max_length=25)),
                ('sku', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=5, max_length=50, prefix='SKU', unique=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('brand', models.CharField(max_length=50)),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Listings',
            },
        ),
        migrations.CreateModel(
            name='ListingsGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='Listing.png', null=True, upload_to='Computer_image')),
                ('gallery_id', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=5, max_length=50, prefix='SKU')),
                ('listing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Marketplace.productlistings')),
            ],
            options={
                'verbose_name_plural': 'ListingsImages',
            },
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='Marketplace.productlistings')),
            ],
            options={
                'verbose_name_plural': 'Specifications',
            },
        ),
    ]
