# Generated by Django 5.1.6 on 2025-03-20 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productlistings',
            options={'verbose_name_plural': 'Products Listings'},
        ),
        migrations.RemoveField(
            model_name='productlistings',
            name='brand',
        ),
    ]
