# Generated by Django 5.1.6 on 2025-03-26 14:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsersProfiles', '0002_rename_userprofile_sellerprofile_certificat_course'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificat',
            name='user',
        ),
        migrations.AddField(
            model_name='certificat',
            name='students',
            field=models.ManyToManyField(related_name='certifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
