# Generated by Django 5.1.6 on 2025-03-27 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsersProfiles', '0003_remove_certificat_user_certificat_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='photo',
            field=models.ImageField(blank=True, default='utilisateur.png', upload_to='profiles/'),
        ),
    ]
