# Generated by Django 5.1.6 on 2025-03-27 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsersProfiles', '0004_alter_sellerprofile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='photo',
            field=models.ImageField(default='PCDeals_api/media/profiles/utilisateur.png', upload_to='profiles/'),
        ),
    ]
