# Generated by Django 5.1.6 on 2025-03-17 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrainingCourses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modules',
            options={'verbose_name_plural': 'Modules'},
        ),
        migrations.AlterModelOptions(
            name='skillslearn',
            options={'verbose_name_plural': 'SkillsLearn'},
        ),
        migrations.AddField(
            model_name='modules',
            name='description',
            field=models.TextField(default='Bienvenue dans ce module'),
        ),
        migrations.AlterField(
            model_name='modules',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='TrainingCourses.course'),
        ),
    ]
