# Generated by Django 5.1.6 on 2025-03-26 14:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrainingCourses', '0007_course_boosted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='modules',
            name='completed_by',
            field=models.ManyToManyField(blank=True, related_name='completed_modules', to=settings.AUTH_USER_MODEL),
        ),
    ]
